class AddError(Exception):
    pass


class FunctionError(Exception):
    pass